# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[directory]
truncation_length = 2
truncation_symbol = "../"
home_symbol = "~"
truncate_to_repo = true
read_only = "🔒"

[aws]
disabled = true

[package]
disabled = true

[custom.dockerctx]
command = "ctx=$(docker context show 2>/dev/null) && [ \"$ctx\" != default ] && printf %s \"$ctx\""
format = "via 🐳 [$output](bold cyan) "
